// Code generated by Kitex v0.5.2. DO NOT EDIT.

package arithmatic

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	arithmatic "github.com/yiwen101/CardWizards/TestRPC/kitex_gen/arithmatic"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Add(ctx context.Context, request *arithmatic.Request, callOptions ...callopt.Option) (r *arithmatic.Response, err error)
	Subtract(ctx context.Context, request *arithmatic.Request, callOptions ...callopt.Option) (r *arithmatic.Response, err error)
	Multiply(ctx context.Context, request *arithmatic.Request, callOptions ...callopt.Option) (r *arithmatic.Response, err error)
	Divide(ctx context.Context, request *arithmatic.Request, callOptions ...callopt.Option) (r *arithmatic.Response, err error)
	TestValidator(ctx context.Context, request *arithmatic.TestValidator, callOptions ...callopt.Option) (r *arithmatic.Response, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kArithmaticClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kArithmaticClient struct {
	*kClient
}

func (p *kArithmaticClient) Add(ctx context.Context, request *arithmatic.Request, callOptions ...callopt.Option) (r *arithmatic.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Add(ctx, request)
}

func (p *kArithmaticClient) Subtract(ctx context.Context, request *arithmatic.Request, callOptions ...callopt.Option) (r *arithmatic.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Subtract(ctx, request)
}

func (p *kArithmaticClient) Multiply(ctx context.Context, request *arithmatic.Request, callOptions ...callopt.Option) (r *arithmatic.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Multiply(ctx, request)
}

func (p *kArithmaticClient) Divide(ctx context.Context, request *arithmatic.Request, callOptions ...callopt.Option) (r *arithmatic.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Divide(ctx, request)
}

func (p *kArithmaticClient) TestValidator(ctx context.Context, request *arithmatic.TestValidator, callOptions ...callopt.Option) (r *arithmatic.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.TestValidator(ctx, request)
}
