// Code generated by Kitex v0.5.2. DO NOT EDIT.
package arithmatic

import (
	server "github.com/cloudwego/kitex/server"
	arithmatic "github.com/yiwen101/CardWizards/TestRPC/kitex_gen/arithmatic"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler arithmatic.Arithmatic, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
