// Code generated by Kitex v0.5.2. DO NOT EDIT.

package arithmatic

import (
	arithmatic "arithmatic/kitex_gen/arithmatic"
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return arithmaticServiceInfo
}

var arithmaticServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "Arithmatic"
	handlerType := (*arithmatic.Arithmatic)(nil)
	methods := map[string]kitex.MethodInfo{
		"Add": kitex.NewMethodInfo(addHandler, newArithmaticAddArgs, newArithmaticAddResult, false),
		"Sub": kitex.NewMethodInfo(subHandler, newArithmaticSubArgs, newArithmaticSubResult, false),
		"Mul": kitex.NewMethodInfo(mulHandler, newArithmaticMulArgs, newArithmaticMulResult, false),
		"Div": kitex.NewMethodInfo(divHandler, newArithmaticDivArgs, newArithmaticDivResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "arithmatic",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.5.2",
		Extra:           extra,
	}
	return svcInfo
}

func addHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*arithmatic.ArithmaticAddArgs)
	realResult := result.(*arithmatic.ArithmaticAddResult)
	success, err := handler.(arithmatic.Arithmatic).Add(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newArithmaticAddArgs() interface{} {
	return arithmatic.NewArithmaticAddArgs()
}

func newArithmaticAddResult() interface{} {
	return arithmatic.NewArithmaticAddResult()
}

func subHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*arithmatic.ArithmaticSubArgs)
	realResult := result.(*arithmatic.ArithmaticSubResult)
	success, err := handler.(arithmatic.Arithmatic).Sub(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newArithmaticSubArgs() interface{} {
	return arithmatic.NewArithmaticSubArgs()
}

func newArithmaticSubResult() interface{} {
	return arithmatic.NewArithmaticSubResult()
}

func mulHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*arithmatic.ArithmaticMulArgs)
	realResult := result.(*arithmatic.ArithmaticMulResult)
	success, err := handler.(arithmatic.Arithmatic).Mul(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newArithmaticMulArgs() interface{} {
	return arithmatic.NewArithmaticMulArgs()
}

func newArithmaticMulResult() interface{} {
	return arithmatic.NewArithmaticMulResult()
}

func divHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*arithmatic.ArithmaticDivArgs)
	realResult := result.(*arithmatic.ArithmaticDivResult)
	success, err := handler.(arithmatic.Arithmatic).Div(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newArithmaticDivArgs() interface{} {
	return arithmatic.NewArithmaticDivArgs()
}

func newArithmaticDivResult() interface{} {
	return arithmatic.NewArithmaticDivResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Add(ctx context.Context, req *arithmatic.Request) (r *arithmatic.Response, err error) {
	var _args arithmatic.ArithmaticAddArgs
	_args.Req = req
	var _result arithmatic.ArithmaticAddResult
	if err = p.c.Call(ctx, "Add", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Sub(ctx context.Context, req *arithmatic.Request) (r *arithmatic.Response, err error) {
	var _args arithmatic.ArithmaticSubArgs
	_args.Req = req
	var _result arithmatic.ArithmaticSubResult
	if err = p.c.Call(ctx, "Sub", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Mul(ctx context.Context, req *arithmatic.Request) (r *arithmatic.Response, err error) {
	var _args arithmatic.ArithmaticMulArgs
	_args.Req = req
	var _result arithmatic.ArithmaticMulResult
	if err = p.c.Call(ctx, "Mul", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Div(ctx context.Context, req *arithmatic.Request) (r *arithmatic.Response, err error) {
	var _args arithmatic.ArithmaticDivArgs
	_args.Req = req
	var _result arithmatic.ArithmaticDivResult
	if err = p.c.Call(ctx, "Div", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
