// Code generated by Kitex v0.5.2. DO NOT EDIT.

package arithmatic

import (
	arithmatic "arithmatic/kitex_gen/arithmatic"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Add(ctx context.Context, req *arithmatic.Request, callOptions ...callopt.Option) (r *arithmatic.Response, err error)
	Sub(ctx context.Context, req *arithmatic.Request, callOptions ...callopt.Option) (r *arithmatic.Response, err error)
	Mul(ctx context.Context, req *arithmatic.Request, callOptions ...callopt.Option) (r *arithmatic.Response, err error)
	Div(ctx context.Context, req *arithmatic.Request, callOptions ...callopt.Option) (r *arithmatic.Response, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kArithmaticClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kArithmaticClient struct {
	*kClient
}

func (p *kArithmaticClient) Add(ctx context.Context, req *arithmatic.Request, callOptions ...callopt.Option) (r *arithmatic.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Add(ctx, req)
}

func (p *kArithmaticClient) Sub(ctx context.Context, req *arithmatic.Request, callOptions ...callopt.Option) (r *arithmatic.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Sub(ctx, req)
}

func (p *kArithmaticClient) Mul(ctx context.Context, req *arithmatic.Request, callOptions ...callopt.Option) (r *arithmatic.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Mul(ctx, req)
}

func (p *kArithmaticClient) Div(ctx context.Context, req *arithmatic.Request, callOptions ...callopt.Option) (r *arithmatic.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Div(ctx, req)
}
