// Code generated by hertz generator.

package arithmatic

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	arithmatic "github.com/yiwen101/CardWizards/biz/model/arithmatic"
)

// Add .
// @router calculator/get [GET]
func Add(ctx context.Context, c *app.RequestContext) {
	var err error
	var req arithmatic.Request
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(arithmatic.Response)

	c.JSON(consts.StatusOK, resp)
}
